require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - bin/bundle
    - vendor/**/*
    - app/controllers/graphql_controller.rb
    - config/database.yml
    - spec/tasks/seeds_spec.rb
    - db/seeds.rb
    - db/schema.rb
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 50
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/graphql/resolvers/freaks_resolver.rb'

Layout/LineLength:
  Exclude:
    - 'app/graphql/resolvers/freaks_resolver.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/graphql/resolvers/freaks_resolver.rb'
