require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - bin/bundle
    - vendor/**/*
    - app/controllers/graphql_controller.rb
  NewCops: enable
