require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - bin/bundle
    - app/controllers/graphql_controller.rb
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 50
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*.rb'
