default: &default
  encoding: UTF-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

staging:
  <<: *default

production:
  <<: *default
